<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>firstLineMatch</key>
	<string>@startuml</string>
	<key>name</key>
	<string>PlantUML</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\s*(@startuml|@enduml)\b</string>
			<key>name</key>
			<string>keyword.control.plantuml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(activate|again|also|alt|as|autonumber|bottom|box|break|center|create|critical|deactivate|destroy|down|else|end|endif|endwhile|footbox|footer|fork|group|header|hide|if|is|left|link|loop|namespace|newpage|note|of|on|opt|over|package|page|par|partition|ref|repeat|return|right|rotate|show|skin|skinparam|start|stop|title|top|top to bottom direction|up|while)\b</string>
			<key>name</key>
			<string>keyword.other.plantuml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(activate|again|also|alt|as|autonumber|bottom|box|break|center|create|critical|deactivate|destroy|down|else|end|endif|endwhile|footbox|footer|fork|group|header|hide|if|is|left|link|loop|namespace|newpage|note|of|on|opt|over|package|page|par|partition|ref|repeat|return|right|rotate|show|skin|skinparam|start|stop|title|top|top to bottom direction|up|while)\b</string>
			<key>name</key>
			<string>constant.language.skinparameter.plantuml</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(activate|again|also|alt|as|autonumber|bottom|box|break|center|create|critical|deactivate|destroy|down|else|end|endif|endwhile|footbox|footer|fork|group|header|hide|if|is|left|link|loop|namespace|newpage|note|of|on|opt|over|package|page|par|partition|ref|repeat|return|right|rotate|show|skin|skinparam|start|stop|title|top|top to bottom direction|up|while)\b</string>
			<key>name</key>
			<string>keyword.other.plantuml</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.plantuml</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\.</string>
					<key>name</key>
					<string>constant.character.escape.plantuml</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.plantuml</string>
	<key>uuid</key>
	<string>63DA15BB-D680-4EDC-A411-A93A199DF523</string>
</dict>
</plist>
